#!/bin/bash
set -e

#############################################
# set AS defaults when running on single JVM
#############################################

CC_HOSTNAME=${CC_HOSTNAME:-"127.0.0.1"}
AS_CC_HTTPS_PORT=${AS_CC_HTTPS_PORT:-"9443"}
SM_HOSTNAME=${SM_HOSTNAME:-"127.0.0.1"}
AS_SM_HTTPS_PORT=${AS_SM_HTTPS_PORT:-"9443"}

###################################
# Echo settings for debug purposes
###################################

echo Setting MB_HOSTNAME=$MB_HOSTNAME 
echo Setting MB_PORT=$MB_PORT
echo =========================
echo Cloud Controller Settings
echo =========================
echo Setting EC2_ENABLED=$EC2_ENABLED
echo Setting EC2_IDENTITY=$EC2_IDENTITY
echo Setting EC2_CREDENTIAL=$EC2_CREDENTIAL
echo Setting EC2_OWNER_ID=$EC2_OWNER_ID
echo Setting EC2_AVAILABILITY_ZONE=$EC2_AVAILABILITY_ZONE
echo Setting EC2_SECURITY_GROUPS=$EC2_SECURITY_GROUPS
echo Setting EC2_KEYPAIR=$EC2_KEYPAIR
echo ===================
echo Autoscaler Settings
echo ===================
echo Setting CC_HOSTNAME=$CC_HOSTNAME
echo Setting AS_CC_HTTPS_PORT=$AS_CC_HTTPS_PORT
echo Setting SM_HOSTNAME=$SM_HOSTNAME
echo Setting AS_SM_HTTPS_PORT=$AS_SM_HTTPS_PORT

export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/

################
# General setup
################

sed -i "s@MB_HOSTNAME:MB_LISTEN_PORT@$MB_HOSTNAME:$MB_PORT@g" ./apache-stratos/repository/conf/jndi.properties

###########
# CC setup
###########

CLOUD_CONTROLLER_CONFIG_FILE=./apache-stratos/repository/conf/cloud-controller.xml

if [[ $EC2_ENABLED = true ]]; then
  sed -i "s@EC2_PROVIDER_START@@g" $CLOUD_CONTROLLER_CONFIG_FILE
  sed -i "s@EC2_IDENTITY@$EC2_IDENTITY@g" $CLOUD_CONTROLLER_CONFIG_FILE
  sed -i "s@EC2_CREDENTIAL@$EC2_CREDENTIAL@g" $CLOUD_CONTROLLER_CONFIG_FILE
  sed -i "s@EC2_OWNER_ID@$EC2_OWNER_ID@g" $CLOUD_CONTROLLER_CONFIG_FILE
  sed -i "s@EC2_AVAILABILITY_ZONE@$EC2_AVAILABILITY_ZONE@g" $CLOUD_CONTROLLER_CONFIG_FILE
  sed -i "s@EC2_SECURITY_GROUPS@$EC2_SECURITY_GROUPS@g" $CLOUD_CONTROLLER_CONFIG_FILE
  sed -i "s@EC2_KEYPAIR@$EC2_KEYPAIR_NAME@g" $CLOUD_CONTROLLER_CONFIG_FILE
  sed -i "s@EC2_PROVIDER_END@@g" $CLOUD_CONTROLLER_CONFIG_FILE
  sed -i "s@OPENSTACK_PROVIDER_START@!--@g" $CLOUD_CONTROLLER_CONFIG_FILE
  sed -i "s@OPENSTACK_PROVIDER_END@--@g" $CLOUD_CONTROLLER_CONFIG_FILE
  sed -i "s@VCLOUD_PROVIDER_START@!--@g" $CLOUD_CONTROLLER_CONFIG_FILE
  sed -i "s@VCLOUD_PROVIDER_END@--@g" $CLOUD_CONTROLLER_CONFIG_FILE
fi

###########
# AS setup
###########

AUTOSCALER_CONFIG_FILE=./apache-stratos/repository/conf/autoscaler.xml

sed -i "s@CC_HOSTNAME@$CC_HOSTNAME@g" $AUTOSCALER_CONFIG_FILE
sed -i "s@CC_LISTEN_PORT@$AS_CC_HTTPS_PORT@g" $AUTOSCALER_CONFIG_FILE
sed -i "s@SM_HOSTNAME@$SM_HOSTNAME@g" $AUTOSCALER_CONFIG_FILE
sed -i "s@SM_LISTEN_PORT@$AS_SM_HTTPS_PORT@g" $AUTOSCALER_CONFIG_FILE

./apache-stratos/bin/stratos.sh -Dprofile=default 
