#!/bin/bash
set -e

echo Setting MB_HOSTNAME=$MB_HOSTNAME 
echo Setting MB_PORT=$MB_PORT
echo Setting EC2_ENABLED=$EC2_ENABLED
echo Setting EC2_IDENTITY=$EC2_IDENTITY
echo Setting EC2_CREDENTIAL=$EC2_CREDENTIAL
echo Setting EC2_OWNER_ID=$EC2_OWNER_ID
echo Setting EC2_AVAILABILITY_ZONE=$EC2_AVAILABILITY_ZONE
echo Setting EC2_SECURITY_GROUPS=$EC2_SECURITY_GROUPS
echo Setting EC2_KEYPAIR=$EC2_KEYPAIR

export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64/

################
# General setup
################

sed -i "s@MB_HOSTNAME:MB_LISTEN_PORT@$MB_HOSTNAME:$MB_PORT@g" ./apache-stratos/repository/conf/jndi.properties

###########
# CC setup
###########

CLOUD_CONTROLLER_FILE=./apache-stratos/repository/conf/cloud-controller.xml

if [[ $EC2_ENABLED = true ]]; then
  sed -i "s@EC2_PROVIDER_START@@g" $CLOUD_CONTROLLER_FILE
  sed -i "s@EC2_IDENTITY@$EC2_IDENTITY@g" $CLOUD_CONTROLLER_FILE
  sed -i "s@EC2_CREDENTIAL@$EC2_CREDENTIAL@g" $CLOUD_CONTROLLER_FILE
  sed -i "s@EC2_OWNER_ID@$EC2_OWNER_ID@g" $CLOUD_CONTROLLER_FILE
  sed -i "s@EC2_AVAILABILITY_ZONE@$EC2_AVAILABILITY_ZONE@g" $CLOUD_CONTROLLER_FILE
  sed -i "s@EC2_SECURITY_GROUPS@$EC2_SECURITY_GROUPS@g" $CLOUD_CONTROLLER_FILE
  sed -i "s@EC2_KEYPAIR@$EC2_KEYPAIR_NAME@g" $CLOUD_CONTROLLER_FILE
  sed -i "s@EC2_PROVIDER_END@@g" $CLOUD_CONTROLLER_FILE
  sed -i "s@OPENSTACK_PROVIDER_START@!--@g" $CLOUD_CONTROLLER_FILE
  sed -i "s@OPENSTACK_PROVIDER_END@--@g" $CLOUD_CONTROLLER_FILE
  sed -i "s@VCLOUD_PROVIDER_START@!--@g" $CLOUD_CONTROLLER_FILE
  sed -i "s@VCLOUD_PROVIDER_END@--@g" $CLOUD_CONTROLLER_FILE
fi

cat $CLOUD_CONTROLLER_FILE

./apache-stratos/bin/stratos.sh -Dprofile=default 
